### PR TITLE
Updated pipeline with slice_timing.

### PR DESCRIPTION
**Pull request by jdtheiss**
Also, this includes an update for create_mesh and other minor changes to supporting functions.

### CODE REVIEW

**Comment by jdtheiss** [comment]
Newest commit is to updated pipeline_JAS to be compatible with other updates.

**Comment by jdtheiss** [comment]
Updated fixHeader to take "eval" statements and pRF_model to take makeStimulus functions.

**Comment by jdtheiss** [comment]
This commit simply allows loop_feval to take '' inputs (specifically, for loop_feval of spm_slice_timing in slice_timing function).

**Comment by Stereo-Boy** [comment]
why taking the number of gray layers to 0 when creating mesh?

**Pull request merged**
